-- Seed de développement
-- Les utilisateurs sont créés via l'auth API ou le dashboard Supabase.
-- Le trigger handle_new_user() créé leur profil automatiquement.
-- Le premier utilisateur créé devient admin et est approuvé.
